# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Playwright GitHub CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Playwright Config
      shell: pwsh
      run: |
        dir ${{ github.workspace }}\EPAM.Playwright.Test\bin\Debug\net6.0
        ${{ github.workspace }}\EPAM.Playwright.Test\bin\Debug\net6.0\playwright.ps1 install    
    - name: Test
      run: dotnet test --no-build --verbosity normal
